<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageReferencesCentrally>true</ManagePackageReferencesCentrally>
  </PropertyGroup>

 

  <ItemGroup>
    <ProjectReference Include="..\..\Infra\Artix.API.Infra.File\Artix.API.Infra.File.csproj"/>
    <ProjectReference Include="..\..\Infra\Artix.API.Infra.Identity\Artix.API.Infra.Identity.csproj"/>
    <ProjectReference Include="..\..\Infra\Artix.API.Infra.RabbitMQ\Artix.API.Infra.RabbitMQ.csproj"/>
    <ProjectReference Include="..\..\Infra\Artix.API.Infra.Redis\Artix.API.Infra.Redis.csproj"/>
    <ProjectReference Include="..\..\Infra\Artix.API.Infra.Sql\Artix.API.Infra.Sql.csproj"/>
    <ProjectReference Include="..\Artix.API.Core.Contract\Artix.API.Core.Contract.csproj"/>
    <ProjectReference Include="..\Artix.API.Core.DomainService\Artix.API.Core.DomainService.csproj"/>
  </ItemGroup>

</Project>
