<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Artix.API.Core.Contract\Artix.API.Core.Contract.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Users\Commands\" />
    <Folder Include="Features\Users\Queries\GetUserProfile\" />
  </ItemGroup>
  
</Project>
