<Project Sdk="Microsoft.NET.Sdk">


  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageReferencesCentrally>true</ManagePackageReferencesCentrally>
  </PropertyGroup>

 

  <ItemGroup>
    <ProjectReference Include="..\..\Infra\Artix.API.Infra.FileService\Artix.API.Infra.FileService.csproj" />
    <ProjectReference Include="..\..\Infra\Artix.API.Infra.Identity\Artix.API.Infra.Identity.csproj"/>
    <ProjectReference Include="..\..\Infra\Artix.API.Infra.RabbitMQ\Artix.API.Infra.RabbitMQ.csproj"/>
    <ProjectReference Include="..\..\Infra\Artix.API.Infra.Redis\Artix.API.Infra.Redis.csproj"/>
    <ProjectReference Include="..\..\Infra\Artix.API.Infra.Sql\Artix.API.Infra.Sql.csproj"/>
    <ProjectReference Include="..\Artix.API.Core.Contract\Artix.API.Core.Contract.csproj"/>
    <ProjectReference Include="..\Artix.API.Core.DomainService\Artix.API.Core.DomainService.csproj"/>
  </ItemGroup>

 

  <ItemGroup>
    <Folder Include="Features\Collections\Client\Commands\" />
    <Folder Include="Features\Museums\Admin\Queries\" />
    <Folder Include="Features\Museums\Client\" />
    <Folder Include="Features\Objects\Admin\Commands\" />
    <Folder Include="Features\Objects\Admin\Queries\" />
    <Folder Include="Features\Objects\Client\Commands\" />
    <Folder Include="Features\Objects\Client\Queries\" />
    <Folder Include="Features\Quizzes\Client\" />
    <Folder Include="Features\Users\Admin\Commands\" />
    <Folder Include="Features\Users\Admin\Queries\" />
    <Folder Include="Features\Users\Client\Queries\" />
    <Folder Include="Features\Versions\Client\" />
  </ItemGroup>

</Project>
