networks:
  internal_net:
    driver: bridge

volumes:
  rabbitmq_data:
  postgres_data:
  dataprotection_keys:
  file_storage:
  mongodb_data:

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - internal_net
    restart: unless-stopped
    healthcheck:
      test: rabbitmqctl status
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Hello&Run1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1434:1433"
    volumes:
      - ./mssql-data:/var/opt/mssql
    networks:
      - internal_net
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: --setParameter authenticationMechanisms=SCRAM-SHA-1,SCRAM-SHA-256
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MongoPass1234
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    user: root
    ports:
      - "6377:6377"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass "Heli@ghar771379"
    networks:
      - internal_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Heli@ghar771379", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artix-api
    ports:
      - "8080:80"                  # بیرون 8080 → داخل کانتینر 80 (همون که داکرفایلت گوش میده)
    depends_on:
      redis:
        condition: service_healthy
      sqlserver:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DOTNET_RUNNING_IN_CONTAINER: "true"
      # هیچ ASPNETCORE_URLS لازم نیست → Kestrel طبق داکرفایل روی 80 گوش میده
    volumes:
      - dataprotection_keys:/app/dataprotection-keys
      - file_storage:/app/files
    networks:
      - internal_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]  # چون داخل کانتینر روی 80 هست
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    extra_hosts:
      - "elasticsearch.drlink.ir:192.168.2.40"
