networks:
  internal_net:
    driver: bridge

volumes:
  rabbitmq_data:
  postgres_data:
  dataprotection_keys:
  file_storage:
  mongodb_data:

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - internal_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 20s

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    user: root
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Hello&Run1234"
      ACCEPT_EULA: "Y"
      MSSQL_PID: Express
    ports:
      - "1434:1433"
    volumes:
      - ./mssql-data:/var/opt/mssql
    networks:
      - internal_net
    restart: unless-stopped

  mongodb:
    image: mongo:latest
    container_name: mongodb
    command: --setParameter authenticationMechanisms=SCRAM-SHA-1,SCRAM-SHA-256
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: MongoPass1234
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - internal_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping').ok\" | grep 1"]
      interval: 5s
      timeout: 3s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    user: root
    ports:
      - "6377:6377"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass "Heli@ghar771379"
    networks:
      - internal_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Heli@ghar771379", "--no-auth-warning", "PING"]
      interval: 5s
      timeout: 3s
      retries: 5

  cluster-watcher:
    image: alpine:3.19
    container_name: cluster-watcher
    depends_on:
      rabbitmq:
        condition: service_healthy
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
      sqlserver:
        condition: service_started
    command: >
      sh -c "
        echo '🔍 Checking cluster health...';
        sleep 3;
        echo '✔ RabbitMQ is stable';
        echo '✔ MongoDB is stable';
        echo '✔ Redis is stable';
        echo '✔ SQL Server started';
        echo '🚀 All clusters stable.';
      "
    networks:
      - internal_net
    restart: "no"

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: artix-api
    ports:
      - "8080:80"
    depends_on:
      cluster-watcher:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      DOTNET_RUNNING_IN_CONTAINER: "true"
    volumes:
      - dataprotection_keys:/app/dataprotection-keys
      - file_storage:/app/files
    networks:
      - internal_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s
    extra_hosts:
      - "elasticsearch.drlink.ir:192.168.2.40"
