worker_processes auto;
worker_rlimit_nofile 65535;

events {
    worker_connections 10240;
    multi_accept on;
    use epoll;
}

http {
    include mime.types;
    default_type application/octet-stream;

    sendfile off;
    tcp_nopush off;
    tcp_nodelay on;

    keepalive_timeout 0;
    keepalive_requests 0;

    server_tokens off;

    # ⛔️ هیچ تغییری روی payload
    gzip off;

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://app1:80;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Connection close;

            # ⛔️ بدون buffer
            proxy_buffering off;
            proxy_request_buffering off;

            # ⛔️ بدون cache در هر شکل
            proxy_cache off;
            proxy_no_cache 1;
            proxy_cache_bypass 1;

            proxy_connect_timeout 5s;
            proxy_send_timeout 20s;
            proxy_read_timeout 20s;
        }

        location /api/shared/upload/ {
            proxy_pass http://app1:80;
            proxy_http_version 1.1;

            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Connection close;

            proxy_request_buffering off;
            proxy_buffering off;

            proxy_cache off;
            proxy_no_cache 1;
            proxy_cache_bypass 1;

            client_max_body_size 8G;

            proxy_connect_timeout 300s;
            proxy_send_timeout 300s;
            proxy_read_timeout 300s;
        }
    }
}
