<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>


  <ItemGroup>
    <PackageReference Include="Polly" />
    <PackageReference Include="Polly.Extensions.Http" />
    <PackageReference Include="Scrutor" />
    <PackageReference Include="MediatR" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="StackExchange.Redis" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\Artix.API.Core.Domain\Artix.API.Core.Domain.csproj" />
  </ItemGroup>


  <ItemGroup>
    <Folder Include="Features\Collections\Client\Commands\" />
    <Folder Include="Features\Museums\Admin\Queries\" />
    <Folder Include="Features\Museums\Client\" />
    <Folder Include="Features\Objects\Admin\Commands\" />
    <Folder Include="Features\Objects\Admin\Queries\" />
    <Folder Include="Features\Objects\Client\Commands\" />
    <Folder Include="Features\Quizzes\Client\" />
    <Folder Include="Features\Tiers\Client\" />
    <Folder Include="Features\Users\Admin\Commands\" />
    <Folder Include="Features\Users\Admin\Queries\" />
  </ItemGroup>
</Project>
