<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer"/>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore"/>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Core\Artix.API.Core.Domain\Artix.API.Core.Domain.csproj"/>
    <ProjectReference Include="..\Artix.API.Infra.Redis\Artix.API.Infra.Redis.csproj" />
    <ProjectReference Include="..\Artix.API.Infra.Sql\Artix.API.Infra.Sql.csproj"/>
  </ItemGroup>

</Project>
