<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.2.1"/>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>b49e7f48-2fdb-423a-87a8-a34888ba7296</UserSecretsId>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost"/>
    <PackageReference Include="Aspire.Hosting"/>
    <PackageReference Include="Aspire.Hosting.Redis"/>
    <PackageReference Include="Aspire.Hosting.RabbitMQ"/>
    <PackageReference Include="Aspire.Hosting.SqlServer"/>
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\src\Presentation\Artix.API.WebService\Artix.API.WebService.csproj"/>
  </ItemGroup>
</Project>

 