name: Build and Push Docker Images

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Build and Push Images
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/nginx:latest ./nginx
        docker push ghcr.io/${{ github.repository_owner }}/nginx:latest

        docker build -t ghcr.io/${{ github.repository_owner }}/redis:latest ./redis
        docker push ghcr.io/${{ github.repository_owner }}/redis:latest

        docker build -t ghcr.io/${{ github.repository_owner }}/mongo:latest ./mongo
        docker push ghcr.io/${{ github.repository_owner }}/mongo:latest

        docker build -t ghcr.io/${{ github.repository_owner }}/rabbitmq:latest ./rabbitmq
        docker push ghcr.io/${{ github.repository_owner }}/rabbitmq:latest
